#!/usr/bin/env node
// === LS Direct-Call Client Generator ===
//
// Reads the extracted RPC registry (tools/api-tracker/schema/rpc-registry.json)
// and emits src/ls-client.js — a thin, typed-by-JSDoc wrapper around the Deck's
// Connect+JSON transport (src/api.js) exposing every LanguageServerService
// method so the Deck/scripts can call the LS directly:
//
//   const { lsClient } = require('./src/ls-client');
//   const diff = await lsClient.getTurnDiff({ conversationId, stepIndex });
//
// Re-run after each Antigravity update (re-extract schema first, then this).
// Output is deterministic + PII-free → committed to git.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const REGISTRY = path.join(__dirname, 'schema', 'rpc-registry.json');
const OUT = path.join(ROOT, 'src', 'ls-client.js');

// Which service to generate. The Deck talks to the Language Server.
const TARGET_FQ = process.argv.includes('--service')
    ? process.argv[process.argv.indexOf('--service') + 1]
    : 'exa.language_server_pb.LanguageServerService';

function camel(name) {
    return name.charAt(0).toLowerCase() + name.slice(1);
}

function jsdoc(m) {
    const streaming = m.kind && m.kind !== 'unary';
    const ret = streaming
        ? `@returns {Promise<{status:number,data:string}>} stream of ${m.output}`
        : `@returns {Promise<object>} ${m.output}`;
    return [
        `  /**`,
        `   * ${m.name}${streaming ? ` (${m.kind})` : ''}`,
        `   * @param {object} [body] ${m.input}`,
        `   * @param {object|null} [inst] LS instance (default: active lsConfig)`,
        `   * ${ret}`,
        `   */`,
    ].join('\n');
}

function main() {
    if (!fs.existsSync(REGISTRY)) {
        console.error(`Registry not found: ${REGISTRY}\nRun the schema extractor first (tools/api-tracker/schema/build-registry.js).`);
        process.exit(1);
    }
    const registry = JSON.parse(fs.readFileSync(REGISTRY, 'utf-8'));
    const svc = registry.find((s) => s.fqService === TARGET_FQ);
    if (!svc || !svc.methods || !svc.methods.length) {
        console.error(`Service ${TARGET_FQ} not found or has no methods in registry.`);
        process.exit(1);
    }

    const methods = svc.methods.slice().sort((a, b) => a.name.localeCompare(b.name));
    const streamingNames = methods.filter((m) => m.kind && m.kind !== 'unary').map((m) => m.name);

    const entries = methods.map((m) => {
        const fn = camel(m.name);
        const streaming = m.kind && m.kind !== 'unary';
        const callExpr = streaming
            ? `callStream('${m.name}', body, inst, timeoutMs)`
            : `call('${m.name}', body, inst)`;
        const sig = streaming
            ? `(body = {}, inst = null, timeoutMs = 60000)`
            : `(body = {}, inst = null)`;
        return `${jsdoc(m)}\n  ${fn}: ${sig} => ${callExpr},`;
    });

    const header = `// === AUTO-GENERATED — DO NOT EDIT BY HAND ===
// Antigravity Language Server direct-call client.
// Generated by tools/api-tracker/gen-client.js from tools/api-tracker/schema/rpc-registry.json
// Service: ${svc.fqService}  |  methods: ${methods.length}  |  streaming: ${streamingNames.length}
// Re-generate after each Antigravity update. Calls go through src/api.js (Connect+JSON).
//
// Usage:
//   const { lsClient } = require('./ls-client');
//   const status = await lsClient.getUserStatus();              // active instance
//   const diff = await lsClient.getTurnDiff({ conversationId, stepIndex }, inst);
`;

    const body = `const { callApi, callApiStream } = require('./api');

/** Unary Connect+JSON call (rejects on HTTP >= 400). */
function call(method, body, inst) { return callApi(method, body || {}, inst); }
/** Server-streaming call: buffers the stream, returns { status, data }. */
function callStream(method, body, inst, timeoutMs) { return callApiStream(method, body || {}, timeoutMs || 60000, inst); }

/** Names of server/client-streaming methods (use the streaming-aware wrappers). */
const STREAMING_METHODS = ${JSON.stringify(streamingNames, null, 0)};

/** Every ${svc.fqService} method, camelCased. */
const lsClient = {
${entries.join('\n')}
};

/** PascalCase method names in this client. */
const LS_METHODS = Object.keys(lsClient).map((k) => k.charAt(0).toUpperCase() + k.slice(1));

module.exports = { lsClient, LS_METHODS, STREAMING_METHODS, LS_SERVICE: '${svc.fqService}' };
`;

    fs.writeFileSync(OUT, `${header}\n${body}`, 'utf-8');
    console.log(`✅ Generated ${path.relative(ROOT, OUT)}`);
    console.log(`   service: ${svc.fqService}`);
    console.log(`   methods: ${methods.length} (${streamingNames.length} streaming)`);
}

main();
