// === AUTO-GENERATED — DO NOT EDIT BY HAND ===
// Antigravity Language Server direct-call client.
// Generated by tools/api-tracker/gen-client.js from tools/api-tracker/schema/rpc-registry.json
// Service: exa.language_server_pb.LanguageServerService  |  methods: 237  |  streaming: 16
// Re-generate after each Antigravity update. Calls go through src/api.js (Connect+JSON).
//
// Usage:
//   const { lsClient } = require('./ls-client');
//   const status = await lsClient.getUserStatus();              // active instance
//   const diff = await lsClient.getTurnDiff({ conversationId, stepIndex }, inst);

const { callApi, callApiStream } = require('./api');

/** Unary Connect+JSON call (rejects on HTTP >= 400). */
function call(method, body, inst) { return callApi(method, body || {}, inst); }
/** Server-streaming call: buffers the stream, returns { status, data }. */
function callStream(method, body, inst, timeoutMs) { return callApiStream(method, body || {}, timeoutMs || 60000, inst); }

/** Names of server/client-streaming methods (use the streaming-aware wrappers). */
const STREAMING_METHODS = ["GetSidecarLogs","HandleStreamingCommand","JetboxSubscribeToGcertState","JetboxSubscribeToOAuthState","JetboxSubscribeToState","JetboxSubscribeToSummaries","ProjectUpdatesStream","StreamAgentStateUpdates","StreamAudioTranscription","StreamCascadePanelReactiveUpdates","StreamCascadeReactiveUpdates","StreamCascadeSummariesReactiveUpdates","StreamTerminalShellCommand","StreamUserTrajectoryReactiveUpdates","SubscribeToSidecars","WatchDirectory"];

/** Every exa.language_server_pb.LanguageServerService method, camelCased. */
const lsClient = {
  /**
   * AcceptTermsOfService
   * @param {object} [body] exa.language_server_pb.AcceptTermsOfServiceRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.AcceptTermsOfServiceResponse
   */
  acceptTermsOfService: (body = {}, inst = null) => call('AcceptTermsOfService', body, inst),
  /**
   * AcknowledgeCascadeCodeEdit
   * @param {object} [body] exa.language_server_pb.AcknowledgeCascadeCodeEditRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.AcknowledgeCascadeCodeEditResponse
   */
  acknowledgeCascadeCodeEdit: (body = {}, inst = null) => call('AcknowledgeCascadeCodeEdit', body, inst),
  /**
   * AcknowledgeCodeActionStep
   * @param {object} [body] exa.language_server_pb.AcknowledgeCodeActionStepRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.AcknowledgeCodeActionStepResponse
   */
  acknowledgeCodeActionStep: (body = {}, inst = null) => call('AcknowledgeCodeActionStep', body, inst),
  /**
   * AddEnvironmentToProject
   * @param {object} [body] exa.language_server_pb.AddEnvironmentToProjectRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.AddEnvironmentToProjectResponse
   */
  addEnvironmentToProject: (body = {}, inst = null) => call('AddEnvironmentToProject', body, inst),
  /**
   * AddToBrowserWhitelist
   * @param {object} [body] exa.language_server_pb.AddToBrowserWhitelistRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.AddToBrowserWhitelistResponse
   */
  addToBrowserWhitelist: (body = {}, inst = null) => call('AddToBrowserWhitelist', body, inst),
  /**
   * AddTrackedWorkspace
   * @param {object} [body] exa.language_server_pb.AddTrackedWorkspaceRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.AddTrackedWorkspaceResponse
   */
  addTrackedWorkspace: (body = {}, inst = null) => call('AddTrackedWorkspace', body, inst),
  /**
   * AuthLogout
   * @param {object} [body] exa.language_server_pb.AuthLogoutRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.AuthLogoutResponse
   */
  authLogout: (body = {}, inst = null) => call('AuthLogout', body, inst),
  /**
   * BrowserValidateCascadeOrCancelOverlay
   * @param {object} [body] exa.language_server_pb.BrowserValidateCascadeOrCancelOverlayRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.BrowserValidateCascadeOrCancelOverlayResponse
   */
  browserValidateCascadeOrCancelOverlay: (body = {}, inst = null) => call('BrowserValidateCascadeOrCancelOverlay', body, inst),
  /**
   * CancelCascadeInvocation
   * @param {object} [body] exa.language_server_pb.CancelCascadeInvocationRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.CancelCascadeInvocationResponse
   */
  cancelCascadeInvocation: (body = {}, inst = null) => call('CancelCascadeInvocation', body, inst),
  /**
   * CancelCascadeSteps
   * @param {object} [body] exa.language_server_pb.CancelCascadeStepsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.CancelCascadeStepsResponse
   */
  cancelCascadeSteps: (body = {}, inst = null) => call('CancelCascadeSteps', body, inst),
  /**
   * CaptureConsoleLogs
   * @param {object} [body] exa.language_server_pb.CaptureConsoleLogsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.CaptureConsoleLogsResponse
   */
  captureConsoleLogs: (body = {}, inst = null) => call('CaptureConsoleLogs', body, inst),
  /**
   * CaptureScreenshot
   * @param {object} [body] exa.language_server_pb.CaptureScreenshotRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.CaptureScreenshotResponse
   */
  captureScreenshot: (body = {}, inst = null) => call('CaptureScreenshot', body, inst),
  /**
   * CheckDevToolsActivePort
   * @param {object} [body] exa.language_server_pb.CheckDevToolsActivePortRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.CheckDevToolsActivePortResponse
   */
  checkDevToolsActivePort: (body = {}, inst = null) => call('CheckDevToolsActivePort', body, inst),
  /**
   * CheckoutWorktree
   * @param {object} [body] exa.language_server_pb.CheckoutWorktreeRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.CheckoutWorktreeResponse
   */
  checkoutWorktree: (body = {}, inst = null) => call('CheckoutWorktree', body, inst),
  /**
   * CompleteMcpOAuth
   * @param {object} [body] exa.language_server_pb.CompleteMcpOAuthRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.CompleteMcpOAuthResponse
   */
  completeMcpOAuth: (body = {}, inst = null) => call('CompleteMcpOAuth', body, inst),
  /**
   * ConvertTrajectoryToMarkdown
   * @param {object} [body] exa.language_server_pb.ConvertTrajectoryToMarkdownRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ConvertTrajectoryToMarkdownResponse
   */
  convertTrajectoryToMarkdown: (body = {}, inst = null) => call('ConvertTrajectoryToMarkdown', body, inst),
  /**
   * CopyBuiltinWorkflowToWorkspace
   * @param {object} [body] exa.language_server_pb.CopyBuiltinWorkflowToWorkspaceRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.CopyBuiltinWorkflowToWorkspaceResponse
   */
  copyBuiltinWorkflowToWorkspace: (body = {}, inst = null) => call('CopyBuiltinWorkflowToWorkspace', body, inst),
  /**
   * CreateCitcWorkspace
   * @param {object} [body] exa.language_server_pb.CreateCitcWorkspaceRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.CreateCitcWorkspaceResponse
   */
  createCitcWorkspace: (body = {}, inst = null) => call('CreateCitcWorkspace', body, inst),
  /**
   * CreateCustomizationFile
   * @param {object} [body] exa.language_server_pb.CreateCustomizationFileRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.CreateCustomizationFileResponse
   */
  createCustomizationFile: (body = {}, inst = null) => call('CreateCustomizationFile', body, inst),
  /**
   * CreateProject
   * @param {object} [body] exa.language_server_pb.CreateProjectRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.CreateProjectResponse
   */
  createProject: (body = {}, inst = null) => call('CreateProject', body, inst),
  /**
   * CreateScratchProjectFolder
   * @param {object} [body] exa.language_server_pb.CreateScratchProjectFolderRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.CreateScratchProjectFolderResponse
   */
  createScratchProjectFolder: (body = {}, inst = null) => call('CreateScratchProjectFolder', body, inst),
  /**
   * CreateTrajectoryShare
   * @param {object} [body] exa.language_server_pb.CreateTrajectoryShareRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.CreateTrajectoryShareResponse
   */
  createTrajectoryShare: (body = {}, inst = null) => call('CreateTrajectoryShare', body, inst),
  /**
   * CreateWorktree
   * @param {object} [body] exa.language_server_pb.CreateWorktreeRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.CreateWorktreeResponse
   */
  createWorktree: (body = {}, inst = null) => call('CreateWorktree', body, inst),
  /**
   * DeleteAgentMessage
   * @param {object} [body] exa.language_server_pb.DeleteAgentMessageRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.DeleteAgentMessageResponse
   */
  deleteAgentMessage: (body = {}, inst = null) => call('DeleteAgentMessage', body, inst),
  /**
   * DeleteCascadeMemory
   * @param {object} [body] exa.language_server_pb.DeleteCascadeMemoryRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.DeleteCascadeMemoryResponse
   */
  deleteCascadeMemory: (body = {}, inst = null) => call('DeleteCascadeMemory', body, inst),
  /**
   * DeleteCascadeTrajectory
   * @param {object} [body] exa.language_server_pb.DeleteCascadeTrajectoryRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.DeleteCascadeTrajectoryResponse
   */
  deleteCascadeTrajectory: (body = {}, inst = null) => call('DeleteCascadeTrajectory', body, inst),
  /**
   * DeleteFileOrDirectory
   * @param {object} [body] exa.language_server_pb.DeleteFileOrDirectoryRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.DeleteFileOrDirectoryResponse
   */
  deleteFileOrDirectory: (body = {}, inst = null) => call('DeleteFileOrDirectory', body, inst),
  /**
   * DeleteMediaArtifact
   * @param {object} [body] exa.language_server_pb.DeleteMediaArtifactRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.DeleteMediaArtifactResponse
   */
  deleteMediaArtifact: (body = {}, inst = null) => call('DeleteMediaArtifact', body, inst),
  /**
   * DeletePlugin
   * @param {object} [body] exa.language_server_pb.DeletePluginRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.DeletePluginResponse
   */
  deletePlugin: (body = {}, inst = null) => call('DeletePlugin', body, inst),
  /**
   * DeleteProject
   * @param {object} [body] exa.language_server_pb.DeleteProjectRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.DeleteProjectResponse
   */
  deleteProject: (body = {}, inst = null) => call('DeleteProject', body, inst),
  /**
   * DeleteQueuedUserInputStep
   * @param {object} [body] exa.language_server_pb.DeleteQueuedUserInputStepRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.DeleteQueuedUserInputStepResponse
   */
  deleteQueuedUserInputStep: (body = {}, inst = null) => call('DeleteQueuedUserInputStep', body, inst),
  /**
   * DeleteWorktree
   * @param {object} [body] exa.language_server_pb.DeleteWorktreeRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.DeleteWorktreeResponse
   */
  deleteWorktree: (body = {}, inst = null) => call('DeleteWorktree', body, inst),
  /**
   * DisconnectMcpOAuth
   * @param {object} [body] exa.language_server_pb.DisconnectMcpOAuthRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.DisconnectMcpOAuthResponse
   */
  disconnectMcpOAuth: (body = {}, inst = null) => call('DisconnectMcpOAuth', body, inst),
  /**
   * DownloadBuildWithGooglePlugin
   * @param {object} [body] exa.language_server_pb.DownloadBuildWithGooglePluginRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.DownloadBuildWithGooglePluginResponse
   */
  downloadBuildWithGooglePlugin: (body = {}, inst = null) => call('DownloadBuildWithGooglePlugin', body, inst),
  /**
   * DumpFlightRecorder
   * @param {object} [body] exa.language_server_pb.DumpFlightRecorderRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.DumpFlightRecorderResponse
   */
  dumpFlightRecorder: (body = {}, inst = null) => call('DumpFlightRecorder', body, inst),
  /**
   * DumpPprof
   * @param {object} [body] exa.language_server_pb.DumpPprofRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.DumpPprofResponse
   */
  dumpPprof: (body = {}, inst = null) => call('DumpPprof', body, inst),
  /**
   * EndAudioSession
   * @param {object} [body] exa.language_server_pb.EndAudioSessionRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.EndAudioSessionResponse
   */
  endAudioSession: (body = {}, inst = null) => call('EndAudioSession', body, inst),
  /**
   * EndBattleMode
   * @param {object} [body] exa.language_server_pb.EndBattleModeRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.EndBattleModeResponse
   */
  endBattleMode: (body = {}, inst = null) => call('EndBattleMode', body, inst),
  /**
   * Exit
   * @param {object} [body] exa.language_server_pb.ExitRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ExitResponse
   */
  exit: (body = {}, inst = null) => call('Exit', body, inst),
  /**
   * FetchUserInfo
   * @param {object} [body] exa.language_server_pb.FetchUserInfoRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.FetchUserInfoResponse
   */
  fetchUserInfo: (body = {}, inst = null) => call('FetchUserInfo', body, inst),
  /**
   * FocusUserPage
   * @param {object} [body] exa.language_server_pb.FocusUserPageRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.FocusUserPageResponse
   */
  focusUserPage: (body = {}, inst = null) => call('FocusUserPage', body, inst),
  /**
   * ForceBackgroundResearchRefresh
   * @param {object} [body] exa.language_server_pb.ForceBackgroundResearchRefreshRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ForceBackgroundResearchRefreshResponse
   */
  forceBackgroundResearchRefresh: (body = {}, inst = null) => call('ForceBackgroundResearchRefresh', body, inst),
  /**
   * ForceStopCascadeTree
   * @param {object} [body] exa.language_server_pb.ForceStopCascadeTreeRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ForceStopCascadeTreeResponse
   */
  forceStopCascadeTree: (body = {}, inst = null) => call('ForceStopCascadeTree', body, inst),
  /**
   * ForkConversation
   * @param {object} [body] exa.language_server_pb.ForkConversationRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ForkConversationResponse
   */
  forkConversation: (body = {}, inst = null) => call('ForkConversation', body, inst),
  /**
   * GenerateCommitMessage
   * @param {object} [body] exa.language_server_pb.GenerateCommitMessageRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GenerateCommitMessageResponse
   */
  generateCommitMessage: (body = {}, inst = null) => call('GenerateCommitMessage', body, inst),
  /**
   * GenerateEnvironmentName
   * @param {object} [body] exa.language_server_pb.GenerateEnvironmentNameRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GenerateEnvironmentNameResponse
   */
  generateEnvironmentName: (body = {}, inst = null) => call('GenerateEnvironmentName', body, inst),
  /**
   * GenerateSkillInstallationCL
   * @param {object} [body] exa.language_server_pb.GenerateSkillInstallationCLRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GenerateSkillInstallationCLResponse
   */
  generateSkillInstallationCL: (body = {}, inst = null) => call('GenerateSkillInstallationCL', body, inst),
  /**
   * GetAgentScripts
   * @param {object} [body] exa.language_server_pb.GetAgentScriptsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetAgentScriptsResponse
   */
  getAgentScripts: (body = {}, inst = null) => call('GetAgentScripts', body, inst),
  /**
   * GetAgentTeamMetadata
   * @param {object} [body] exa.language_server_pb.GetAgentTeamMetadataRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetAgentTeamMetadataResponse
   */
  getAgentTeamMetadata: (body = {}, inst = null) => call('GetAgentTeamMetadata', body, inst),
  /**
   * GetAllBrowserWhitelistedUrls
   * @param {object} [body] exa.language_server_pb.GetAllBrowserWhitelistedUrlsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetAllBrowserWhitelistedUrlsResponse
   */
  getAllBrowserWhitelistedUrls: (body = {}, inst = null) => call('GetAllBrowserWhitelistedUrls', body, inst),
  /**
   * GetAllCascadeTrajectories
   * @param {object} [body] exa.language_server_pb.GetAllCascadeTrajectoriesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetAllCascadeTrajectoriesResponse
   */
  getAllCascadeTrajectories: (body = {}, inst = null) => call('GetAllCascadeTrajectories', body, inst),
  /**
   * GetAllCustomAgentConfigs
   * @param {object} [body] exa.language_server_pb.GetAllCustomAgentConfigsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetAllCustomAgentConfigsResponse
   */
  getAllCustomAgentConfigs: (body = {}, inst = null) => call('GetAllCustomAgentConfigs', body, inst),
  /**
   * GetAllPlugins
   * @param {object} [body] exa.language_server_pb.GetAllPluginsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetAllPluginsResponse
   */
  getAllPlugins: (body = {}, inst = null) => call('GetAllPlugins', body, inst),
  /**
   * GetAllRules
   * @param {object} [body] exa.language_server_pb.GetAllRulesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetAllRulesResponse
   */
  getAllRules: (body = {}, inst = null) => call('GetAllRules', body, inst),
  /**
   * GetAllSkills
   * @param {object} [body] exa.language_server_pb.GetAllSkillsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetAllSkillsResponse
   */
  getAllSkills: (body = {}, inst = null) => call('GetAllSkills', body, inst),
  /**
   * GetAllWorkflows
   * @param {object} [body] exa.language_server_pb.GetAllWorkflowsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetAllWorkflowsResponse
   */
  getAllWorkflows: (body = {}, inst = null) => call('GetAllWorkflows', body, inst),
  /**
   * GetArtifactSnapshots
   * @param {object} [body] exa.language_server_pb.GetArtifactSnapshotsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetArtifactSnapshotsResponse
   */
  getArtifactSnapshots: (body = {}, inst = null) => call('GetArtifactSnapshots', body, inst),
  /**
   * GetAuthStatus
   * @param {object} [body] exa.language_server_pb.GetAuthStatusRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetAuthStatusResponse
   */
  getAuthStatus: (body = {}, inst = null) => call('GetAuthStatus', body, inst),
  /**
   * GetAvailableCascadePlugins
   * @param {object} [body] exa.language_server_pb.GetAvailableCascadePluginsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetAvailableCascadePluginsResponse
   */
  getAvailableCascadePlugins: (body = {}, inst = null) => call('GetAvailableCascadePlugins', body, inst),
  /**
   * GetAvailableModels
   * @param {object} [body] exa.language_server_pb.GetAvailableModelsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetAvailableModelsResponse
   */
  getAvailableModels: (body = {}, inst = null) => call('GetAvailableModels', body, inst),
  /**
   * GetBrowserOpenConversation
   * @param {object} [body] exa.language_server_pb.GetBrowserOpenConversationRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetBrowserOpenConversationResponse
   */
  getBrowserOpenConversation: (body = {}, inst = null) => call('GetBrowserOpenConversation', body, inst),
  /**
   * GetBrowserWhitelistFilePath
   * @param {object} [body] exa.language_server_pb.GetBrowserWhitelistFilePathRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetBrowserWhitelistFilePathResponse
   */
  getBrowserWhitelistFilePath: (body = {}, inst = null) => call('GetBrowserWhitelistFilePath', body, inst),
  /**
   * GetBuildWithGooglePlugins
   * @param {object} [body] exa.language_server_pb.GetBuildWithGooglePluginsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetBuildWithGooglePluginsResponse
   */
  getBuildWithGooglePlugins: (body = {}, inst = null) => call('GetBuildWithGooglePlugins', body, inst),
  /**
   * GetCascadeMemories
   * @param {object} [body] exa.language_server_pb.GetCascadeMemoriesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetCascadeMemoriesResponse
   */
  getCascadeMemories: (body = {}, inst = null) => call('GetCascadeMemories', body, inst),
  /**
   * GetCascadeModelConfigData
   * @param {object} [body] exa.language_server_pb.GetCascadeModelConfigDataRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.codeium_common_pb.CascadeModelConfigData
   */
  getCascadeModelConfigData: (body = {}, inst = null) => call('GetCascadeModelConfigData', body, inst),
  /**
   * GetCascadeModelConfigs
   * @param {object} [body] exa.language_server_pb.GetCascadeModelConfigsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetCascadeModelConfigsResponse
   */
  getCascadeModelConfigs: (body = {}, inst = null) => call('GetCascadeModelConfigs', body, inst),
  /**
   * GetCascadeNuxes
   * @param {object} [body] exa.language_server_pb.GetCascadeNuxesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetCascadeNuxesResponse
   */
  getCascadeNuxes: (body = {}, inst = null) => call('GetCascadeNuxes', body, inst),
  /**
   * GetCascadePluginById
   * @param {object} [body] exa.language_server_pb.GetCascadePluginByIdRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetCascadePluginByIdResponse
   */
  getCascadePluginById: (body = {}, inst = null) => call('GetCascadePluginById', body, inst),
  /**
   * GetCascadeTrajectory
   * @param {object} [body] exa.language_server_pb.GetCascadeTrajectoryRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetCascadeTrajectoryResponse
   */
  getCascadeTrajectory: (body = {}, inst = null) => call('GetCascadeTrajectory', body, inst),
  /**
   * GetCascadeTrajectoryExecutorMetadatas
   * @param {object} [body] exa.language_server_pb.GetCascadeTrajectoryExecutorMetadatasRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetCascadeTrajectoryExecutorMetadatasResponse
   */
  getCascadeTrajectoryExecutorMetadatas: (body = {}, inst = null) => call('GetCascadeTrajectoryExecutorMetadatas', body, inst),
  /**
   * GetCascadeTrajectoryGeneratorMetadata
   * @param {object} [body] exa.language_server_pb.GetCascadeTrajectoryGeneratorMetadataRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetCascadeTrajectoryGeneratorMetadataResponse
   */
  getCascadeTrajectoryGeneratorMetadata: (body = {}, inst = null) => call('GetCascadeTrajectoryGeneratorMetadata', body, inst),
  /**
   * GetCascadeTrajectorySteps
   * @param {object} [body] exa.language_server_pb.GetCascadeTrajectoryStepsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetCascadeTrajectoryStepsResponse
   */
  getCascadeTrajectorySteps: (body = {}, inst = null) => call('GetCascadeTrajectorySteps', body, inst),
  /**
   * GetChangelog
   * @param {object} [body] exa.language_server_pb.GetChangelogRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetChangelogResponse
   */
  getChangelog: (body = {}, inst = null) => call('GetChangelog', body, inst),
  /**
   * GetCodeFrequencyForRepo
   * @param {object} [body] exa.language_server_pb.GetCodeFrequencyForRepoRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetCodeFrequencyForRepoResponse
   */
  getCodeFrequencyForRepo: (body = {}, inst = null) => call('GetCodeFrequencyForRepo', body, inst),
  /**
   * GetCodeValidationStates
   * @param {object} [body] exa.language_server_pb.GetCodeValidationStatesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetCodeValidationStatesResponse
   */
  getCodeValidationStates: (body = {}, inst = null) => call('GetCodeValidationStates', body, inst),
  /**
   * GetCommandModelConfigs
   * @param {object} [body] exa.language_server_pb.GetCommandModelConfigsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetCommandModelConfigsResponse
   */
  getCommandModelConfigs: (body = {}, inst = null) => call('GetCommandModelConfigs', body, inst),
  /**
   * GetConversationMetadata
   * @param {object} [body] exa.language_server_pb.GetConversationMetadataRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetConversationMetadataResponse
   */
  getConversationMetadata: (body = {}, inst = null) => call('GetConversationMetadata', body, inst),
  /**
   * GetDebugDiagnostics
   * @param {object} [body] exa.language_server_pb.GetDebugDiagnosticsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetDebugDiagnosticsResponse
   */
  getDebugDiagnostics: (body = {}, inst = null) => call('GetDebugDiagnostics', body, inst),
  /**
   * GetDefaultProjectDir
   * @param {object} [body] exa.language_server_pb.GetDefaultProjectDirRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetDefaultProjectDirResponse
   */
  getDefaultProjectDir: (body = {}, inst = null) => call('GetDefaultProjectDir', body, inst),
  /**
   * GetGrantedScopes
   * @param {object} [body] exa.language_server_pb.GetGrantedScopesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetGrantedScopesResponse
   */
  getGrantedScopes: (body = {}, inst = null) => call('GetGrantedScopes', body, inst),
  /**
   * GetKnowledgeItems
   * @param {object} [body] exa.language_server_pb.GetKnowledgeItemsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetKnowledgeItemsResponse
   */
  getKnowledgeItems: (body = {}, inst = null) => call('GetKnowledgeItems', body, inst),
  /**
   * GetLoadCodeAssist
   * @param {object} [body] exa.language_server_pb.GetLoadCodeAssistRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetLoadCodeAssistResponse
   */
  getLoadCodeAssist: (body = {}, inst = null) => call('GetLoadCodeAssist', body, inst),
  /**
   * GetLocalUserInfo
   * @param {object} [body] exa.language_server_pb.GetLocalUserInfoRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetLocalUserInfoResponse
   */
  getLocalUserInfo: (body = {}, inst = null) => call('GetLocalUserInfo', body, inst),
  /**
   * GetMatchingContextScopeItems
   * @param {object} [body] exa.language_server_pb.GetMatchingContextScopeItemsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetMatchingContextScopeItemsResponse
   */
  getMatchingContextScopeItems: (body = {}, inst = null) => call('GetMatchingContextScopeItems', body, inst),
  /**
   * GetMcpPrompt
   * @param {object} [body] exa.language_server_pb.GetMcpPromptRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetMcpPromptResponse
   */
  getMcpPrompt: (body = {}, inst = null) => call('GetMcpPrompt', body, inst),
  /**
   * GetMcpServerStates
   * @param {object} [body] exa.language_server_pb.GetMcpServerStatesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetMcpServerStatesResponse
   */
  getMcpServerStates: (body = {}, inst = null) => call('GetMcpServerStates', body, inst),
  /**
   * GetMcpServerTemplates
   * @param {object} [body] exa.language_server_pb.GetMcpServerTemplatesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetMcpServerTemplatesResponse
   */
  getMcpServerTemplates: (body = {}, inst = null) => call('GetMcpServerTemplates', body, inst),
  /**
   * GetMendelFlags
   * @param {object} [body] exa.language_server_pb.GetMendelFlagsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetMendelFlagsResponse
   */
  getMendelFlags: (body = {}, inst = null) => call('GetMendelFlags', body, inst),
  /**
   * GetModelResponse
   * @param {object} [body] exa.language_server_pb.GetModelResponseRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetModelResponseResponse
   */
  getModelResponse: (body = {}, inst = null) => call('GetModelResponse', body, inst),
  /**
   * GetModelStatuses
   * @param {object} [body] exa.language_server_pb.GetModelStatusesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetModelStatusesResponse
   */
  getModelStatuses: (body = {}, inst = null) => call('GetModelStatuses', body, inst),
  /**
   * GetPatchAndCodeChange
   * @param {object} [body] exa.language_server_pb.GetPatchAndCodeChangeRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetPatchAndCodeChangeResponse
   */
  getPatchAndCodeChange: (body = {}, inst = null) => call('GetPatchAndCodeChange', body, inst),
  /**
   * GetProfileData
   * @param {object} [body] exa.language_server_pb.GetProfileDataRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetProfileDataResponse
   */
  getProfileData: (body = {}, inst = null) => call('GetProfileData', body, inst),
  /**
   * GetRepoInfos
   * @param {object} [body] exa.language_server_pb.GetRepoInfosRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetRepoInfosResponse
   */
  getRepoInfos: (body = {}, inst = null) => call('GetRepoInfos', body, inst),
  /**
   * GetRevertPreview
   * @param {object} [body] exa.language_server_pb.GetRevertPreviewRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetRevertPreviewResponse
   */
  getRevertPreview: (body = {}, inst = null) => call('GetRevertPreview', body, inst),
  /**
   * GetRevisionArtifact
   * @param {object} [body] exa.language_server_pb.GetRevisionArtifactRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetRevisionArtifactResponse
   */
  getRevisionArtifact: (body = {}, inst = null) => call('GetRevisionArtifact', body, inst),
  /**
   * GetSidecarEvents
   * @param {object} [body] exa.language_server_pb.GetSidecarEventsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetSidecarEventsResponse
   */
  getSidecarEvents: (body = {}, inst = null) => call('GetSidecarEvents', body, inst),
  /**
   * GetSidecarLogs (server_streaming)
   * @param {object} [body] exa.language_server_pb.GetSidecarLogsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<{status:number,data:string}>} stream of exa.language_server_pb.GetSidecarLogsResponse
   */
  getSidecarLogs: (body = {}, inst = null, timeoutMs = 60000) => callStream('GetSidecarLogs', body, inst, timeoutMs),
  /**
   * GetSidecars
   * @param {object} [body] exa.language_server_pb.GetSidecarsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetSidecarsResponse
   */
  getSidecars: (body = {}, inst = null) => call('GetSidecars', body, inst),
  /**
   * GetSkillMarketplaceLink
   * @param {object} [body] exa.language_server_pb.GetSkillMarketplaceLinkRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetSkillMarketplaceLinkResponse
   */
  getSkillMarketplaceLink: (body = {}, inst = null) => call('GetSkillMarketplaceLink', body, inst),
  /**
   * GetSlashCommands
   * @param {object} [body] exa.language_server_pb.GetSlashCommandsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetSlashCommandsResponse
   */
  getSlashCommands: (body = {}, inst = null) => call('GetSlashCommands', body, inst),
  /**
   * GetStandaloneDir
   * @param {object} [body] exa.language_server_pb.GetStandaloneDirRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetStandaloneDirResponse
   */
  getStandaloneDir: (body = {}, inst = null) => call('GetStandaloneDir', body, inst),
  /**
   * GetStaticExperimentStatus
   * @param {object} [body] exa.language_server_pb.GetStaticExperimentStatusRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetStaticExperimentStatusResponse
   */
  getStaticExperimentStatus: (body = {}, inst = null) => call('GetStaticExperimentStatus', body, inst),
  /**
   * GetStatus
   * @param {object} [body] exa.language_server_pb.GetStatusRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetStatusResponse
   */
  getStatus: (body = {}, inst = null) => call('GetStatus', body, inst),
  /**
   * GetTeamOrganizationalControls
   * @param {object} [body] exa.language_server_pb.GetTeamOrganizationalControlsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetTeamOrganizationalControlsResponse
   */
  getTeamOrganizationalControls: (body = {}, inst = null) => call('GetTeamOrganizationalControls', body, inst),
  /**
   * GetTermsOfService
   * @param {object} [body] exa.language_server_pb.GetTermsOfServiceRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetTermsOfServiceResponse
   */
  getTermsOfService: (body = {}, inst = null) => call('GetTermsOfService', body, inst),
  /**
   * GetTokenBase
   * @param {object} [body] exa.language_server_pb.GetTokenBaseRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetTokenBaseResponse
   */
  getTokenBase: (body = {}, inst = null) => call('GetTokenBase', body, inst),
  /**
   * GetTranscription
   * @param {object} [body] exa.language_server_pb.GetTranscriptionRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetTranscriptionResponse
   */
  getTranscription: (body = {}, inst = null) => call('GetTranscription', body, inst),
  /**
   * GetTurnDiff
   * @param {object} [body] exa.language_server_pb.GetTurnDiffRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetTurnDiffResponse
   */
  getTurnDiff: (body = {}, inst = null) => call('GetTurnDiff', body, inst),
  /**
   * GetUnleashData
   * @param {object} [body] exa.language_server_pb.GetUnleashDataRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetUnleashDataResponse
   */
  getUnleashData: (body = {}, inst = null) => call('GetUnleashData', body, inst),
  /**
   * GetUserAnalyticsSummary
   * @param {object} [body] exa.language_server_pb.GetUserAnalyticsSummaryRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetUserAnalyticsSummaryResponse
   */
  getUserAnalyticsSummary: (body = {}, inst = null) => call('GetUserAnalyticsSummary', body, inst),
  /**
   * GetUserMemories
   * @param {object} [body] exa.language_server_pb.GetUserMemoriesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetUserMemoriesResponse
   */
  getUserMemories: (body = {}, inst = null) => call('GetUserMemories', body, inst),
  /**
   * GetUserSettings
   * @param {object} [body] exa.language_server_pb.GetUserSettingsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetUserSettingsResponse
   */
  getUserSettings: (body = {}, inst = null) => call('GetUserSettings', body, inst),
  /**
   * GetUserStatus
   * @param {object} [body] exa.language_server_pb.GetUserStatusRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetUserStatusResponse
   */
  getUserStatus: (body = {}, inst = null) => call('GetUserStatus', body, inst),
  /**
   * GetUserTrajectory
   * @param {object} [body] exa.language_server_pb.GetUserTrajectoryRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetUserTrajectoryResponse
   */
  getUserTrajectory: (body = {}, inst = null) => call('GetUserTrajectory', body, inst),
  /**
   * GetUserTrajectoryDebug
   * @param {object} [body] exa.language_server_pb.GetUserTrajectoryDebugRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetUserTrajectoryDebugResponse
   */
  getUserTrajectoryDebug: (body = {}, inst = null) => call('GetUserTrajectoryDebug', body, inst),
  /**
   * GetUserTrajectoryDescriptions
   * @param {object} [body] exa.language_server_pb.GetUserTrajectoryDescriptionsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetUserTrajectoryDescriptionsResponse
   */
  getUserTrajectoryDescriptions: (body = {}, inst = null) => call('GetUserTrajectoryDescriptions', body, inst),
  /**
   * GetWebDocsOptions
   * @param {object} [body] exa.language_server_pb.GetWebDocsOptionsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetWebDocsOptionsResponse
   */
  getWebDocsOptions: (body = {}, inst = null) => call('GetWebDocsOptions', body, inst),
  /**
   * GetWorkingDirectories
   * @param {object} [body] exa.language_server_pb.GetWorkingDirectoriesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetWorkingDirectoriesResponse
   */
  getWorkingDirectories: (body = {}, inst = null) => call('GetWorkingDirectories', body, inst),
  /**
   * GetWorkspaceEditState
   * @param {object} [body] exa.language_server_pb.GetWorkspaceEditStateRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetWorkspaceEditStateResponse
   */
  getWorkspaceEditState: (body = {}, inst = null) => call('GetWorkspaceEditState', body, inst),
  /**
   * GetWorkspaceInfos
   * @param {object} [body] exa.language_server_pb.GetWorkspaceInfosRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetWorkspaceInfosResponse
   */
  getWorkspaceInfos: (body = {}, inst = null) => call('GetWorkspaceInfos', body, inst),
  /**
   * GetWorktreeDiff
   * @param {object} [body] exa.language_server_pb.GetWorktreeDiffRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.GetWorktreeDiffResponse
   */
  getWorktreeDiff: (body = {}, inst = null) => call('GetWorktreeDiff', body, inst),
  /**
   * HandleCascadeUserInteraction
   * @param {object} [body] exa.language_server_pb.HandleCascadeUserInteractionRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.HandleCascadeUserInteractionResponse
   */
  handleCascadeUserInteraction: (body = {}, inst = null) => call('HandleCascadeUserInteraction', body, inst),
  /**
   * HandleScreenRecording
   * @param {object} [body] exa.language_server_pb.HandleScreenRecordingRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.HandleScreenRecordingResponse
   */
  handleScreenRecording: (body = {}, inst = null) => call('HandleScreenRecording', body, inst),
  /**
   * HandleStreamingCommand (server_streaming)
   * @param {object} [body] exa.language_server_pb.HandleStreamingCommandRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<{status:number,data:string}>} stream of exa.language_server_pb.HandleStreamingCommandResponse
   */
  handleStreamingCommand: (body = {}, inst = null, timeoutMs = 60000) => callStream('HandleStreamingCommand', body, inst, timeoutMs),
  /**
   * HasAuthToken
   * @param {object} [body] exa.language_server_pb.HasAuthTokenRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.HasAuthTokenResponse
   */
  hasAuthToken: (body = {}, inst = null) => call('HasAuthToken', body, inst),
  /**
   * Heartbeat
   * @param {object} [body] exa.language_server_pb.HeartbeatRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.HeartbeatResponse
   */
  heartbeat: (body = {}, inst = null) => call('Heartbeat', body, inst),
  /**
   * ImportFromCursor
   * @param {object} [body] exa.language_server_pb.ImportFromCursorRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ImportFromCursorResponse
   */
  importFromCursor: (body = {}, inst = null) => call('ImportFromCursor', body, inst),
  /**
   * ImportProjectFromUrl
   * @param {object} [body] exa.language_server_pb.ImportProjectFromUrlRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ImportProjectFromUrlResponse
   */
  importProjectFromUrl: (body = {}, inst = null) => call('ImportProjectFromUrl', body, inst),
  /**
   * InitializeCascadePanelState
   * @param {object} [body] exa.language_server_pb.InitializeCascadePanelStateRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.InitializeCascadePanelStateResponse
   */
  initializeCascadePanelState: (body = {}, inst = null) => call('InitializeCascadePanelState', body, inst),
  /**
   * InstallCascadePlugin
   * @param {object} [body] exa.language_server_pb.InstallCascadePluginRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.InstallCascadePluginResponse
   */
  installCascadePlugin: (body = {}, inst = null) => call('InstallCascadePlugin', body, inst),
  /**
   * JetboxDeleteSummary
   * @param {object} [body] exa.language_server_pb.JetboxDeleteSummaryRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.JetboxDeleteSummaryResponse
   */
  jetboxDeleteSummary: (body = {}, inst = null) => call('JetboxDeleteSummary', body, inst),
  /**
   * JetboxGetLatestVersion
   * @param {object} [body] exa.language_server_pb.JetboxGetLatestVersionRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.JetboxGetLatestVersionResponse
   */
  jetboxGetLatestVersion: (body = {}, inst = null) => call('JetboxGetLatestVersion', body, inst),
  /**
   * JetboxSubscribeToGcertState (server_streaming)
   * @param {object} [body] exa.language_server_pb.JetboxSubscribeToGcertStateRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<{status:number,data:string}>} stream of exa.language_server_pb.JetboxSubscribeToGcertStateResponse
   */
  jetboxSubscribeToGcertState: (body = {}, inst = null, timeoutMs = 60000) => callStream('JetboxSubscribeToGcertState', body, inst, timeoutMs),
  /**
   * JetboxSubscribeToOAuthState (server_streaming)
   * @param {object} [body] exa.language_server_pb.JetboxSubscribeToOAuthStateRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<{status:number,data:string}>} stream of exa.language_server_pb.JetboxSubscribeToOAuthStateResponse
   */
  jetboxSubscribeToOAuthState: (body = {}, inst = null, timeoutMs = 60000) => callStream('JetboxSubscribeToOAuthState', body, inst, timeoutMs),
  /**
   * JetboxSubscribeToState (server_streaming)
   * @param {object} [body] exa.language_server_pb.JetboxSubscribeToStateRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<{status:number,data:string}>} stream of exa.language_server_pb.JetboxSubscribeToStateResponse
   */
  jetboxSubscribeToState: (body = {}, inst = null, timeoutMs = 60000) => callStream('JetboxSubscribeToState', body, inst, timeoutMs),
  /**
   * JetboxSubscribeToSummaries (server_streaming)
   * @param {object} [body] exa.language_server_pb.JetboxSubscribeToSummariesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<{status:number,data:string}>} stream of exa.language_server_pb.JetboxSubscribeToSummariesResponse
   */
  jetboxSubscribeToSummaries: (body = {}, inst = null, timeoutMs = 60000) => callStream('JetboxSubscribeToSummaries', body, inst, timeoutMs),
  /**
   * JetboxWriteState
   * @param {object} [body] exa.language_server_pb.JetboxWriteStateRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.JetboxWriteStateResponse
   */
  jetboxWriteState: (body = {}, inst = null) => call('JetboxWriteState', body, inst),
  /**
   * JetboxWriteSummary
   * @param {object} [body] exa.language_server_pb.JetboxWriteSummaryRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.JetboxWriteSummaryResponse
   */
  jetboxWriteSummary: (body = {}, inst = null) => call('JetboxWriteSummary', body, inst),
  /**
   * ListCustomizationPathsByFile
   * @param {object} [body] exa.language_server_pb.ListCustomizationPathsByFileRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ListCustomizationPathsByFileResponse
   */
  listCustomizationPathsByFile: (body = {}, inst = null) => call('ListCustomizationPathsByFile', body, inst),
  /**
   * ListMcpPrompts
   * @param {object} [body] exa.language_server_pb.ListMcpPromptsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ListMcpPromptsResponse
   */
  listMcpPrompts: (body = {}, inst = null) => call('ListMcpPrompts', body, inst),
  /**
   * ListMcpResources
   * @param {object} [body] exa.language_server_pb.ListMcpResourcesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ListMcpResourcesResponse
   */
  listMcpResources: (body = {}, inst = null) => call('ListMcpResources', body, inst),
  /**
   * ListPages
   * @param {object} [body] exa.language_server_pb.ListPagesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ListPagesResponse
   */
  listPages: (body = {}, inst = null) => call('ListPages', body, inst),
  /**
   * ListSidecarLogFiles
   * @param {object} [body] exa.language_server_pb.ListSidecarLogFilesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ListSidecarLogFilesResponse
   */
  listSidecarLogFiles: (body = {}, inst = null) => call('ListSidecarLogFiles', body, inst),
  /**
   * LoadReplayConversation
   * @param {object} [body] exa.language_server_pb.LoadReplayConversationRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.LoadReplayConversationResponse
   */
  loadReplayConversation: (body = {}, inst = null) => call('LoadReplayConversation', body, inst),
  /**
   * LoadTrajectory
   * @param {object} [body] exa.language_server_pb.LoadTrajectoryRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.LoadTrajectoryResponse
   */
  loadTrajectory: (body = {}, inst = null) => call('LoadTrajectory', body, inst),
  /**
   * LoginWithBrowser
   * @param {object} [body] exa.language_server_pb.LoginWithBrowserRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.LoginWithBrowserResponse
   */
  loginWithBrowser: (body = {}, inst = null) => call('LoginWithBrowser', body, inst),
  /**
   * ManageSidecar
   * @param {object} [body] exa.language_server_pb.ManageSidecarRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ManageSidecarResponse
   */
  manageSidecar: (body = {}, inst = null) => call('ManageSidecar', body, inst),
  /**
   * MigrateApiKey
   * @param {object} [body] exa.language_server_pb.MigrateApiKeyRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.MigrateApiKeyResponse
   */
  migrateApiKey: (body = {}, inst = null) => call('MigrateApiKey', body, inst),
  /**
   * OpenUrl
   * @param {object} [body] exa.language_server_pb.OpenUrlRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.OpenUrlResponse
   */
  openUrl: (body = {}, inst = null) => call('OpenUrl', body, inst),
  /**
   * ProjectUpdatesStream (server_streaming)
   * @param {object} [body] exa.language_server_pb.ProjectUpdatesStreamRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<{status:number,data:string}>} stream of exa.language_server_pb.ProjectUpdatesStreamResponse
   */
  projectUpdatesStream: (body = {}, inst = null, timeoutMs = 60000) => callStream('ProjectUpdatesStream', body, inst, timeoutMs),
  /**
   * ProvideCompletionFeedback
   * @param {object} [body] exa.language_server_pb.ProvideCompletionFeedbackRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ProvideCompletionFeedbackResponse
   */
  provideCompletionFeedback: (body = {}, inst = null) => call('ProvideCompletionFeedback', body, inst),
  /**
   * ReadDir
   * @param {object} [body] exa.language_server_pb.ReadDirRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ReadDirResponse
   */
  readDir: (body = {}, inst = null) => call('ReadDir', body, inst),
  /**
   * ReadFile
   * @param {object} [body] exa.language_server_pb.ReadFileRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ReadFileResponse
   */
  readFile: (body = {}, inst = null) => call('ReadFile', body, inst),
  /**
   * ReadProject
   * @param {object} [body] exa.language_server_pb.ReadProjectRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ReadProjectResponse
   */
  readProject: (body = {}, inst = null) => call('ReadProject', body, inst),
  /**
   * ReconnectExtensionServer
   * @param {object} [body] exa.language_server_pb.ReconnectExtensionServerRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ReconnectExtensionServerResponse
   */
  reconnectExtensionServer: (body = {}, inst = null) => call('ReconnectExtensionServer', body, inst),
  /**
   * RecordAnalyticsEvent
   * @param {object} [body] exa.language_server_pb.RecordAnalyticsEventRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RecordAnalyticsEventResponse
   */
  recordAnalyticsEvent: (body = {}, inst = null) => call('RecordAnalyticsEvent', body, inst),
  /**
   * RecordChatFeedback
   * @param {object} [body] exa.language_server_pb.RecordChatFeedbackRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RecordChatFeedbackResponse
   */
  recordChatFeedback: (body = {}, inst = null) => call('RecordChatFeedback', body, inst),
  /**
   * RecordChatPanelSession
   * @param {object} [body] exa.language_server_pb.RecordChatPanelSessionRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RecordChatPanelSessionResponse
   */
  recordChatPanelSession: (body = {}, inst = null) => call('RecordChatPanelSession', body, inst),
  /**
   * RecordCommitMessageSave
   * @param {object} [body] exa.language_server_pb.RecordCommitMessageSaveRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RecordCommitMessageSaveResponse
   */
  recordCommitMessageSave: (body = {}, inst = null) => call('RecordCommitMessageSave', body, inst),
  /**
   * RecordError
   * @param {object} [body] exa.language_server_pb.RecordErrorRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RecordErrorResponse
   */
  recordError: (body = {}, inst = null) => call('RecordError', body, inst),
  /**
   * RecordEvent
   * @param {object} [body] exa.language_server_pb.RecordEventRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RecordEventResponse
   */
  recordEvent: (body = {}, inst = null) => call('RecordEvent', body, inst),
  /**
   * RecordInteractiveCascadeFeedback
   * @param {object} [body] exa.language_server_pb.RecordInteractiveCascadeFeedbackRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RecordInteractiveCascadeFeedbackResponse
   */
  recordInteractiveCascadeFeedback: (body = {}, inst = null) => call('RecordInteractiveCascadeFeedback', body, inst),
  /**
   * RecordLints
   * @param {object} [body] exa.language_server_pb.RecordLintsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RecordLintsResponse
   */
  recordLints: (body = {}, inst = null) => call('RecordLints', body, inst),
  /**
   * RecordObservabilityData
   * @param {object} [body] exa.language_server_pb.RecordObservabilityDataRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RecordObservabilityDataResponse
   */
  recordObservabilityData: (body = {}, inst = null) => call('RecordObservabilityData', body, inst),
  /**
   * RecordSearchDocOpen
   * @param {object} [body] exa.language_server_pb.RecordSearchDocOpenRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RecordSearchDocOpenResponse
   */
  recordSearchDocOpen: (body = {}, inst = null) => call('RecordSearchDocOpen', body, inst),
  /**
   * RecordSearchResultsView
   * @param {object} [body] exa.language_server_pb.RecordSearchResultsViewRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RecordSearchResultsViewResponse
   */
  recordSearchResultsView: (body = {}, inst = null) => call('RecordSearchResultsView', body, inst),
  /**
   * RecordSidecarEvent
   * @param {object} [body] exa.language_server_pb.RecordSidecarEventRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RecordSidecarEventResponse
   */
  recordSidecarEvent: (body = {}, inst = null) => call('RecordSidecarEvent', body, inst),
  /**
   * RecordUserGrep
   * @param {object} [body] exa.language_server_pb.RecordUserGrepRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RecordUserGrepResponse
   */
  recordUserGrep: (body = {}, inst = null) => call('RecordUserGrep', body, inst),
  /**
   * RecordUserStepSnapshot
   * @param {object} [body] exa.language_server_pb.RecordUserStepSnapshotRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RecordUserStepSnapshotResponse
   */
  recordUserStepSnapshot: (body = {}, inst = null) => call('RecordUserStepSnapshot', body, inst),
  /**
   * RefreshContextForIdeAction
   * @param {object} [body] exa.language_server_pb.RefreshContextForIdeActionRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RefreshContextForIdeActionResponse
   */
  refreshContextForIdeAction: (body = {}, inst = null) => call('RefreshContextForIdeAction', body, inst),
  /**
   * RefreshMcpServers
   * @param {object} [body] exa.language_server_pb.RefreshMcpServersRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RefreshMcpServersResponse
   */
  refreshMcpServers: (body = {}, inst = null) => call('RefreshMcpServers', body, inst),
  /**
   * RegisterGdmUser
   * @param {object} [body] exa.language_server_pb.RegisterGdmUserRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RegisterGdmUserResponse
   */
  registerGdmUser: (body = {}, inst = null) => call('RegisterGdmUser', body, inst),
  /**
   * RegisterInteraction
   * @param {object} [body] exa.language_server_pb.RegisterInteractionRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RegisterInteractionResponse
   */
  registerInteraction: (body = {}, inst = null) => call('RegisterInteraction', body, inst),
  /**
   * RemoveTrackedWorkspace
   * @param {object} [body] exa.language_server_pb.RemoveTrackedWorkspaceRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RemoveTrackedWorkspaceResponse
   */
  removeTrackedWorkspace: (body = {}, inst = null) => call('RemoveTrackedWorkspace', body, inst),
  /**
   * ReplayGroundTruthTrajectory
   * @param {object} [body] exa.language_server_pb.ReplayGroundTruthTrajectoryRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ReplayGroundTruthTrajectoryResponse
   */
  replayGroundTruthTrajectory: (body = {}, inst = null) => call('ReplayGroundTruthTrajectory', body, inst),
  /**
   * RequestAgentStatePageUpdate
   * @param {object} [body] exa.jetski_cortex_pb.AgentStatePageUpdateRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.jetski_cortex_pb.AgentStatePageUpdateResponse
   */
  requestAgentStatePageUpdate: (body = {}, inst = null) => call('RequestAgentStatePageUpdate', body, inst),
  /**
   * ResetOnboarding
   * @param {object} [body] exa.language_server_pb.ResetOnboardingRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ResetOnboardingResponse
   */
  resetOnboarding: (body = {}, inst = null) => call('ResetOnboarding', body, inst),
  /**
   * ResolveFolder
   * @param {object} [body] exa.language_server_pb.ResolveFolderRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ResolveFolderResponse
   */
  resolveFolder: (body = {}, inst = null) => call('ResolveFolder', body, inst),
  /**
   * ResolveOutstandingSteps
   * @param {object} [body] exa.language_server_pb.ResolveOutstandingStepsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ResolveOutstandingStepsResponse
   */
  resolveOutstandingSteps: (body = {}, inst = null) => call('ResolveOutstandingSteps', body, inst),
  /**
   * ResolveWorkspaceUrlPreview
   * @param {object} [body] exa.language_server_pb.ResolveWorkspaceUrlPreviewRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ResolveWorkspaceUrlPreviewResponse
   */
  resolveWorkspaceUrlPreview: (body = {}, inst = null) => call('ResolveWorkspaceUrlPreview', body, inst),
  /**
   * Restart
   * @param {object} [body] exa.language_server_pb.RestartRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RestartResponse
   */
  restart: (body = {}, inst = null) => call('Restart', body, inst),
  /**
   * RevertToCascadeStep
   * @param {object} [body] exa.language_server_pb.RevertToCascadeStepRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RevertToCascadeStepResponse
   */
  revertToCascadeStep: (body = {}, inst = null) => call('RevertToCascadeStep', body, inst),
  /**
   * RunCommand
   * @param {object} [body] exa.language_server_pb.RunCommandRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.RunCommandResponse
   */
  runCommand: (body = {}, inst = null) => call('RunCommand', body, inst),
  /**
   * SaveAgentScriptCommandSpec
   * @param {object} [body] exa.language_server_pb.SaveAgentScriptCommandSpecRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SaveAgentScriptCommandSpecResponse
   */
  saveAgentScriptCommandSpec: (body = {}, inst = null) => call('SaveAgentScriptCommandSpec', body, inst),
  /**
   * SaveMediaAsArtifact
   * @param {object} [body] exa.language_server_pb.SaveMediaAsArtifactRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SaveMediaAsArtifactResponse
   */
  saveMediaAsArtifact: (body = {}, inst = null) => call('SaveMediaAsArtifact', body, inst),
  /**
   * SaveScreenRecording
   * @param {object} [body] exa.language_server_pb.SaveScreenRecordingRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SaveScreenRecordingResponse
   */
  saveScreenRecording: (body = {}, inst = null) => call('SaveScreenRecording', body, inst),
  /**
   * ScanSkillsConfigFile
   * @param {object} [body] exa.language_server_pb.ScanSkillsConfigFileRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ScanSkillsConfigFileResponse
   */
  scanSkillsConfigFile: (body = {}, inst = null) => call('ScanSkillsConfigFile', body, inst),
  /**
   * SearchCode
   * @param {object} [body] exa.language_server_pb.SearchCodeRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SearchCodeResponse
   */
  searchCode: (body = {}, inst = null) => call('SearchCode', body, inst),
  /**
   * SearchConversations
   * @param {object} [body] exa.language_server_pb.SearchConversationsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SearchConversationsResponse
   */
  searchConversations: (body = {}, inst = null) => call('SearchConversations', body, inst),
  /**
   * SearchFiles
   * @param {object} [body] exa.language_server_pb.SearchFilesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SearchFilesResponse
   */
  searchFiles: (body = {}, inst = null) => call('SearchFiles', body, inst),
  /**
   * SendActionToChatPanel
   * @param {object} [body] exa.language_server_pb.SendActionToChatPanelRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SendActionToChatPanelResponse
   */
  sendActionToChatPanel: (body = {}, inst = null) => call('SendActionToChatPanel', body, inst),
  /**
   * SendAgentMessage
   * @param {object} [body] exa.language_server_pb.SendAgentMessageRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SendAgentMessageResponse
   */
  sendAgentMessage: (body = {}, inst = null) => call('SendAgentMessage', body, inst),
  /**
   * SendAllQueuedMessages
   * @param {object} [body] exa.language_server_pb.SendAllQueuedMessagesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SendAllQueuedMessagesResponse
   */
  sendAllQueuedMessages: (body = {}, inst = null) => call('SendAllQueuedMessages', body, inst),
  /**
   * SendAudioChunk
   * @param {object} [body] exa.language_server_pb.SendAudioChunkRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SendAudioChunkResponse
   */
  sendAudioChunk: (body = {}, inst = null) => call('SendAudioChunk', body, inst),
  /**
   * SendStepsToBackground
   * @param {object} [body] exa.language_server_pb.SendStepsToBackgroundRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SendStepsToBackgroundResponse
   */
  sendStepsToBackground: (body = {}, inst = null) => call('SendStepsToBackground', body, inst),
  /**
   * SendUserCascadeMessage
   * @param {object} [body] exa.language_server_pb.SendUserCascadeMessageRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SendUserCascadeMessageResponse
   */
  sendUserCascadeMessage: (body = {}, inst = null) => call('SendUserCascadeMessage', body, inst),
  /**
   * SetBaseExperiments
   * @param {object} [body] exa.language_server_pb.SetBaseExperimentsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SetBaseExperimentsResponse
   */
  setBaseExperiments: (body = {}, inst = null) => call('SetBaseExperiments', body, inst),
  /**
   * SetBrowserOpenConversation
   * @param {object} [body] exa.language_server_pb.SetBrowserOpenConversationRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SetBrowserOpenConversationResponse
   */
  setBrowserOpenConversation: (body = {}, inst = null) => call('SetBrowserOpenConversation', body, inst),
  /**
   * SetCloudCodeURL
   * @param {object} [body] exa.language_server_pb.SetCloudCodeURLRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SetCloudCodeURLResponse
   */
  setCloudCodeURL: (body = {}, inst = null) => call('SetCloudCodeURL', body, inst),
  /**
   * SetOrVerifyStaticConfig
   * @param {object} [body] exa.language_server_pb.SetOrVerifyStaticConfigRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SetOrVerifyStaticConfigResponse
   */
  setOrVerifyStaticConfig: (body = {}, inst = null) => call('SetOrVerifyStaticConfig', body, inst),
  /**
   * SetupUniversitySandbox
   * @param {object} [body] exa.language_server_pb.SetupUniversitySandboxRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SetupUniversitySandboxResponse
   */
  setupUniversitySandbox: (body = {}, inst = null) => call('SetupUniversitySandbox', body, inst),
  /**
   * SetUserInfo
   * @param {object} [body] exa.language_server_pb.SetUserInfoRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SetUserInfoResponse
   */
  setUserInfo: (body = {}, inst = null) => call('SetUserInfo', body, inst),
  /**
   * SetUserSettings
   * @param {object} [body] exa.language_server_pb.SetUserSettingsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SetUserSettingsResponse
   */
  setUserSettings: (body = {}, inst = null) => call('SetUserSettings', body, inst),
  /**
   * SetWorkingDirectories
   * @param {object} [body] exa.language_server_pb.SetWorkingDirectoriesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SetWorkingDirectoriesResponse
   */
  setWorkingDirectories: (body = {}, inst = null) => call('SetWorkingDirectories', body, inst),
  /**
   * ShouldEnableUnleash
   * @param {object} [body] exa.language_server_pb.ShouldEnableUnleashRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ShouldEnableUnleashResponse
   */
  shouldEnableUnleash: (body = {}, inst = null) => call('ShouldEnableUnleash', body, inst),
  /**
   * SignalExecutableIdle
   * @param {object} [body] exa.language_server_pb.SignalExecutableIdleRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SignalExecutableIdleResponse
   */
  signalExecutableIdle: (body = {}, inst = null) => call('SignalExecutableIdle', body, inst),
  /**
   * SimulateSegFault
   * @param {object} [body] exa.language_server_pb.SimulateSegFaultRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SimulateSegFaultResponse
   */
  simulateSegFault: (body = {}, inst = null) => call('SimulateSegFault', body, inst),
  /**
   * SkipBrowserSubagent
   * @param {object} [body] exa.language_server_pb.SkipBrowserSubagentRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SkipBrowserSubagentResponse
   */
  skipBrowserSubagent: (body = {}, inst = null) => call('SkipBrowserSubagent', body, inst),
  /**
   * SkipOnboarding
   * @param {object} [body] exa.language_server_pb.SkipOnboardingRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SkipOnboardingResponse
   */
  skipOnboarding: (body = {}, inst = null) => call('SkipOnboarding', body, inst),
  /**
   * SmartFocusConversation
   * @param {object} [body] exa.language_server_pb.SmartFocusConversationRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SmartFocusConversationResponse
   */
  smartFocusConversation: (body = {}, inst = null) => call('SmartFocusConversation', body, inst),
  /**
   * SmartOpenBrowser
   * @param {object} [body] exa.language_server_pb.SmartOpenBrowserRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.SmartOpenBrowserResponse
   */
  smartOpenBrowser: (body = {}, inst = null) => call('SmartOpenBrowser', body, inst),
  /**
   * StartBattleMode
   * @param {object} [body] exa.language_server_pb.StartBattleModeRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.StartBattleModeResponse
   */
  startBattleMode: (body = {}, inst = null) => call('StartBattleMode', body, inst),
  /**
   * StartCascade
   * @param {object} [body] exa.language_server_pb.StartCascadeRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.StartCascadeResponse
   */
  startCascade: (body = {}, inst = null) => call('StartCascade', body, inst),
  /**
   * StartScreenRecording
   * @param {object} [body] exa.language_server_pb.StartScreenRecordingRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.StartScreenRecordingResponse
   */
  startScreenRecording: (body = {}, inst = null) => call('StartScreenRecording', body, inst),
  /**
   * StatUri
   * @param {object} [body] exa.language_server_pb.StatUriRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.StatUriResponse
   */
  statUri: (body = {}, inst = null) => call('StatUri', body, inst),
  /**
   * StreamAgentStateUpdates (server_streaming)
   * @param {object} [body] exa.jetski_cortex_pb.StreamAgentStateUpdatesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<{status:number,data:string}>} stream of exa.jetski_cortex_pb.StreamAgentStateUpdatesResponse
   */
  streamAgentStateUpdates: (body = {}, inst = null, timeoutMs = 60000) => callStream('StreamAgentStateUpdates', body, inst, timeoutMs),
  /**
   * StreamAudioTranscription (server_streaming)
   * @param {object} [body] exa.language_server_pb.StartAudioTranscriptionRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<{status:number,data:string}>} stream of exa.language_server_pb.StreamAudioTranscriptionResponse
   */
  streamAudioTranscription: (body = {}, inst = null, timeoutMs = 60000) => callStream('StreamAudioTranscription', body, inst, timeoutMs),
  /**
   * StreamCascadePanelReactiveUpdates (server_streaming)
   * @param {object} [body] exa.reactive_component_pb.StreamReactiveUpdatesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<{status:number,data:string}>} stream of exa.reactive_component_pb.StreamReactiveUpdatesResponse
   */
  streamCascadePanelReactiveUpdates: (body = {}, inst = null, timeoutMs = 60000) => callStream('StreamCascadePanelReactiveUpdates', body, inst, timeoutMs),
  /**
   * StreamCascadeReactiveUpdates (server_streaming)
   * @param {object} [body] exa.reactive_component_pb.StreamReactiveUpdatesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<{status:number,data:string}>} stream of exa.reactive_component_pb.StreamReactiveUpdatesResponse
   */
  streamCascadeReactiveUpdates: (body = {}, inst = null, timeoutMs = 60000) => callStream('StreamCascadeReactiveUpdates', body, inst, timeoutMs),
  /**
   * StreamCascadeSummariesReactiveUpdates (server_streaming)
   * @param {object} [body] exa.reactive_component_pb.StreamReactiveUpdatesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<{status:number,data:string}>} stream of exa.reactive_component_pb.StreamReactiveUpdatesResponse
   */
  streamCascadeSummariesReactiveUpdates: (body = {}, inst = null, timeoutMs = 60000) => callStream('StreamCascadeSummariesReactiveUpdates', body, inst, timeoutMs),
  /**
   * StreamTerminalShellCommand (client_streaming)
   * @param {object} [body] exa.codeium_common_pb.TerminalShellCommandStreamChunk
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<{status:number,data:string}>} stream of exa.language_server_pb.StreamTerminalShellCommandResponse
   */
  streamTerminalShellCommand: (body = {}, inst = null, timeoutMs = 60000) => callStream('StreamTerminalShellCommand', body, inst, timeoutMs),
  /**
   * StreamUserTrajectoryReactiveUpdates (server_streaming)
   * @param {object} [body] exa.reactive_component_pb.StreamReactiveUpdatesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<{status:number,data:string}>} stream of exa.reactive_component_pb.StreamReactiveUpdatesResponse
   */
  streamUserTrajectoryReactiveUpdates: (body = {}, inst = null, timeoutMs = 60000) => callStream('StreamUserTrajectoryReactiveUpdates', body, inst, timeoutMs),
  /**
   * SubscribeToSidecars (server_streaming)
   * @param {object} [body] exa.language_server_pb.SubscribeToSidecarsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<{status:number,data:string}>} stream of exa.language_server_pb.SubscribeToSidecarsResponse
   */
  subscribeToSidecars: (body = {}, inst = null, timeoutMs = 60000) => callStream('SubscribeToSidecars', body, inst, timeoutMs),
  /**
   * ToggleMcpServer
   * @param {object} [body] exa.language_server_pb.ToggleMcpServerRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ToggleMcpServerResponse
   */
  toggleMcpServer: (body = {}, inst = null) => call('ToggleMcpServer', body, inst),
  /**
   * UpdateCascadeMemory
   * @param {object} [body] exa.language_server_pb.UpdateCascadeMemoryRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.UpdateCascadeMemoryResponse
   */
  updateCascadeMemory: (body = {}, inst = null) => call('UpdateCascadeMemory', body, inst),
  /**
   * UpdateConversationAnnotations
   * @param {object} [body] exa.language_server_pb.UpdateConversationAnnotationsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.UpdateConversationAnnotationsResponse
   */
  updateConversationAnnotations: (body = {}, inst = null) => call('UpdateConversationAnnotations', body, inst),
  /**
   * UpdateCustomization
   * @param {object} [body] exa.language_server_pb.UpdateCustomizationRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.UpdateCustomizationResponse
   */
  updateCustomization: (body = {}, inst = null) => call('UpdateCustomization', body, inst),
  /**
   * UpdateCustomizationPathsFile
   * @param {object} [body] exa.language_server_pb.UpdateCustomizationPathsFileRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.UpdateCustomizationPathsFileResponse
   */
  updateCustomizationPathsFile: (body = {}, inst = null) => call('UpdateCustomizationPathsFile', body, inst),
  /**
   * UpdateDevExperiments
   * @param {object} [body] exa.language_server_pb.UpdateDevExperimentsRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.UpdateDevExperimentsResponse
   */
  updateDevExperiments: (body = {}, inst = null) => call('UpdateDevExperiments', body, inst),
  /**
   * UpdateEnterpriseExperimentsFromUrl
   * @param {object} [body] exa.language_server_pb.UpdateEnterpriseExperimentsFromUrlRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.UpdateEnterpriseExperimentsFromUrlResponse
   */
  updateEnterpriseExperimentsFromUrl: (body = {}, inst = null) => call('UpdateEnterpriseExperimentsFromUrl', body, inst),
  /**
   * UpdatePRForWorktree
   * @param {object} [body] exa.language_server_pb.UpdatePRForWorktreeRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.UpdatePRForWorktreeResponse
   */
  updatePRForWorktree: (body = {}, inst = null) => call('UpdatePRForWorktree', body, inst),
  /**
   * UpdateProject
   * @param {object} [body] exa.language_server_pb.UpdateProjectRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.UpdateProjectResponse
   */
  updateProject: (body = {}, inst = null) => call('UpdateProject', body, inst),
  /**
   * ValidateProject
   * @param {object} [body] exa.language_server_pb.ValidateProjectRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.ValidateProjectResponse
   */
  validateProject: (body = {}, inst = null) => call('ValidateProject', body, inst),
  /**
   * WaitForConversationFullyIdle
   * @param {object} [body] exa.language_server_pb.WaitForConversationFullyIdleRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.WaitForConversationFullyIdleResponse
   */
  waitForConversationFullyIdle: (body = {}, inst = null) => call('WaitForConversationFullyIdle', body, inst),
  /**
   * WatchDirectory (server_streaming)
   * @param {object} [body] exa.language_server_pb.WatchDirectoryRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<{status:number,data:string}>} stream of exa.language_server_pb.WatchDirectoryResponse
   */
  watchDirectory: (body = {}, inst = null, timeoutMs = 60000) => callStream('WatchDirectory', body, inst, timeoutMs),
  /**
   * WellSupportedLanguages
   * @param {object} [body] exa.language_server_pb.WellSupportedLanguagesRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.WellSupportedLanguagesResponse
   */
  wellSupportedLanguages: (body = {}, inst = null) => call('WellSupportedLanguages', body, inst),
  /**
   * WriteFile
   * @param {object} [body] exa.language_server_pb.WriteFileRequest
   * @param {object|null} [inst] LS instance (default: active lsConfig)
   * @returns {Promise<object>} exa.language_server_pb.WriteFileResponse
   */
  writeFile: (body = {}, inst = null) => call('WriteFile', body, inst),
};

/** PascalCase method names in this client. */
const LS_METHODS = Object.keys(lsClient).map((k) => k.charAt(0).toUpperCase() + k.slice(1));

module.exports = { lsClient, LS_METHODS, STREAMING_METHODS, LS_SERVICE: 'exa.language_server_pb.LanguageServerService' };
